# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve [--baseurl '']'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: BusinessCasePlaybook
description: Business Case Playbook website
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://businesscaseplaybook.service.gov.au/" # the base hostname & protocol for your site, e.g. http://example.com


collections:
  plays:
    output: true
    permalink: /plays/:path/
    order:
      - establish-your-team.html
      - engage-your-sponsors.html
      - scope-the-preliminary-work.html
      - understand-the-problem.html
      - engage-stakeholders-early-and-often.html
      - explore-options.html
      - define-options.html
      - select-your-preferred-solution.html
      - draft-your-business-case.html
      - maintain-the-business-case.html
  main-pages:
    output: true
    permalink: /:path/

collections_dir: _pages

permalink: pretty

# Build settings
markdown: kramdown
#include: ["_pages"]
exclude: ["_pages/plays", "node_modules", "gulpfile.js", "package.json","package-lock.json", "pancake", "vsCodeWorkspace.code-workspace","LICENSE","README.md"]
plugins:
    - jekyll-minifier
jekyll-minifier:
  exclude: ["assets/css/*.css","*.min.*","assets/js/*.js","manifest.yml", "Staticfile"]
