baseurl: ""
exclude: ["node_modules", "gulpfile.js", "package.json","package-lock.json", "pancake", "vsCodeWorkspace.code-workspace","LICENSE","README.md"]
jekyll-minifier:
  exclude: ["assets/css/*.css","*.min.*","assets/js/*.js","manifest.yml", "Staticfile"]
