---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: 
sections:
- type: jekyll-posts
  label: Pages collection
  create: documents
  match: "**/*"
- type: jekyll-pages
  label: Home page
  create: all
- type: directory
  path: _main-pages
  label: Main pages
  create: all
  match: "**/*"
- type: directory
  path: _plays
  label: Plays
  create: all
  match: "*"
upload_dir: uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_env:
  - JEKYLL_ENV=staging
  preview_output_directory: _site
  install_dependencies_command: bundle install --path vendor/bundle
  preview_docker_image: forestryio/ruby:2.6
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: bundle exec jekyll serve --trace --drafts --unpublished
    --future -d _site
