---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: 
sections:
- type: document
  path: https://github.com/govau/oecd-business-case-playbook/tree/master/_data/menus.yml
  label: Menus
  match: "**/*"
- type: document
  path: index.md
  label: Home
- type: directory
  path: _pages/_main-pages
  label: Main pages
  create: documents
  match: "*.md"
  templates:
  - page
- type: directory
  path: _pages/_plays
  label: Plays
  create: documents
  match: "*.md"
upload_dir: uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_env:
  - JEKYLL_ENV=staging
  preview_output_directory: _site
  install_dependencies_command: bundle install --path vendor/bundle
  preview_docker_image: forestryio/ruby:2.6-node12
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: bundle exec jekyll serve --trace --drafts --unpublished
    --future -d _site
